"""
Django settings for qlnh_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import firebase_admin
from firebase_admin import credentials

cred = credentials.Certificate("moon-acce5-firebase-adminsdk-fbsvc-db191d447e.json")
firebase_admin.initialize_app(cred)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = BASE_DIR / 'images'
MEDIA_URL = '/images/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$#gr3z_pl4@(e_etbwipki&wjx$-h_v2po!cwjv+at_i-$+7do'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'oauth2_provider',
    'rest_framework',
    'restaurant.apps.RestaurantConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Use custom user model defined in restaurant.models
AUTH_USER_MODEL = 'restaurant.NguoiDung'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qlnh_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qlnh_backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'quanlynhahang',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': ''
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Múi giờ mặc định của project (ở đây đặt theo Việt Nam: UTC+7).
# - Nếu USE_TZ = False: Django sẽ dùng múi giờ này như tham chiếu cho các
#   datetime "naive" (không có thông tin timezone) khi lưu và hiển thị.
# - Nếu USE_TZ = True: Django lưu timestamp trong DB ở UTC, rồi khi hiển
#   thị sẽ chuyển sang múi giờ này (hoặc timezone của user nếu được cấu hình).
TIME_ZONE = 'Asia/Ho_Chi_Minh'

# Bật tính năng quốc tế hóa (i18n) — cho phép dùng hệ thống dịch (gettext)
# và các template tag như {% trans %}. Giữ True nếu muốn hỗ trợ đa ngôn ngữ.
USE_I18N = True

# Bật/tắt hỗ trợ timezone-aware datetimes.
# - USE_TZ = True: Django dùng datetime có timezone (aware), lưu dữ liệu ở UTC
#   trong DB và chuyển đổi theo TIME_ZONE khi hiển thị. Đây là best practice
#   nếu ứng dụng có người dùng ở nhiều múi giờ hoặc production.
# - USE_TZ = False: Django dùng datetime naive (không timezone) và tham chiếu
#   theo TIME_ZONE;
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
