# Generated by Django 5.2.6 on 2025-09-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_ban', models.IntegerField(unique=True)),
                ('suc_chua', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True, help_text='Có sẵn để gọi món')),
            ],
        ),
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nguyen_lieu', models.CharField(max_length=100)),
                ('so_luong', models.FloatField()),
                ('don_vi', models.CharField(max_length=50)),
                ('threshold', models.FloatField(default=0, help_text='Mức cảnh báo khi số lượng dưới mức này')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(max_length=15, unique=True)),
                ('mat_khau', models.CharField(max_length=255)),
                ('ho_ten', models.CharField(max_length=100)),
                ('chuc_vu', models.CharField(choices=[('waiter', 'Phục vụ'), ('manager', 'Quản lý'), ('chef', 'Đầu bếp'), ('cashier', 'Thu ngân')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('canceled', 'Đã hủy')], max_length=50)),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('ban_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.banan')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='NguyenLieuLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_thay_doi', models.FloatField()),
                ('loai', models.CharField(choices=[('nhap', 'Nhập kho'), ('su_dung', 'Sử dụng'), ('huy', 'Hủy bỏ')], max_length=50)),
                ('mon_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.monan')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.nguyenlieu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('ban_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.banan')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.khachhang')),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ')], max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia', models.IntegerField()),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.monan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order')),
            ],
        ),
    ]
