# Generated by Django 5.2.6 on 2025-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banan',
            name='khu_vuc',
            field=models.CharField(choices=[('inside', 'Trong nhà'), ('outside', 'Ngoài trời'), ('private-room', 'VIP')], default='inside', max_length=50),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='loai_nguoi_dung',
            field=models.CharField(choices=[('khach_hang', 'Khách hàng'), ('nhan_vien', 'Nhân viên')], default='khach_hang', max_length=50),
        ),
    ]
