# Generated by Django 5.2.6 on 2025-09-22 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_banan_khu_vuc_alter_nguoidung_loai_nguoi_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachVangLai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ngay_dat',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='donhang',
            name='khach_vang_lai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.khachvanglai'),
        ),
        migrations.AddField(
            model_name='order',
            name='khach_vang_lai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.khachvanglai'),
        ),
    ]
