# Generated by Django 5.2.6 on 2025-09-23 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_khachvanglai_alter_donhang_khach_hang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietorder',
            name='trang_thai',
            field=models.CharField(choices=[('dang-lam', 'Đang làm'), ('hoan-thanh', 'Hoàn thành')], default='dang-lam', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='khach_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
