# Generated by Django 5.2.6 on 2025-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_chitietorder_trang_thai_alter_order_khach_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietorder',
            name='trang_thai',
            field=models.CharField(choices=[('dang-doi', 'Chờ chế biến'), ('dang-lam', 'Đang làm'), ('hoan-thanh', 'Hoàn thành')], default='dang-doi', max_length=30),
        ),
    ]
