# Generated by Django 5.2.6 on 2025-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_chitietorder_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='monan',
            name='hinh_anh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
