# Generated by Django 5.2.6 on 2025-09-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_monan_hinh_anh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguyenlieulog',
            name='mon_an',
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khach_vang_lai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.khachvanglai'),
        ),
        migrations.AlterField(
            model_name='monan',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_an', to='restaurant.danhmuc'),
        ),
        migrations.AlterField(
            model_name='order',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='khach_vang_lai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.khachvanglai'),
        ),
    ]
