# Generated by Django 5.2.6 on 2025-09-26 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_nguyenlieulog_mon_an_alter_donhang_khach_hang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='ca_lam',
            field=models.CharField(blank=True, choices=[('sang', 'Ca sáng (8:00-14:00)'), ('chieu', 'Ca chiều (14:00-20:00)'), ('dem', 'Ca đêm (20:00-24:00)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='dang_lam_viec',
            field=models.BooleanField(default=False, help_text='Nhân viên có đang trong ca làm việc'),
        ),
        migrations.AddField(
            model_name='order',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loai_order',
            field=models.CharField(choices=[('dine_in', 'Ăn tại chỗ'), ('takeaway', 'Mang về')], default='dine_in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='thoi_gian_lay',
            field=models.IntegerField(blank=True, help_text='Thời gian ước tính lấy món (phút)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='thoi_gian_san_sang',
            field=models.DateTimeField(blank=True, help_text='Thời gian món sẵn sàng', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trang_thai',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cooking', 'Đang nấu'), ('ready', 'Sẵn sàng'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='ban_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.banan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_handled', to=settings.AUTH_USER_MODEL),
        ),
    ]
