# Generated by Django 5.2.6 on 2025-10-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_nguoidung_ca_lam_nguoidung_dang_lam_viec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietorder',
            name='trang_thai',
        ),
    ]
