# Generated by Django 5.2.6 on 2025-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_fcmdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('noi_dung', models.TextField()),
                ('public', models.BooleanField(default=True, help_text='Có hiển thị nội dung này trên ứng dụng không')),
                ('content_type', models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh')], default='text', max_length=255)),
            ],
        ),
    ]
