# Generated by Django 5.2.6 on 2025-10-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content_type',
            field=models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('html', 'HTML'), ('json', 'JSON')], default='text', max_length=255),
        ),
    ]
