# Generated by Django 5.2.6 on 2025-10-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_order_thoi_gian_khach_lay_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dia_chi_giao_hang',
            field=models.TextField(blank=True, help_text='Địa chỉ giao hàng (chỉ áp dụng khi chọn giao hàng tận nơi)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phuong_thuc_giao_hang',
            field=models.CharField(blank=True, choices=[('pickup', 'Tự đến lấy'), ('delivery', 'Giao hàng tận nơi')], help_text='Phương thức giao hàng (chỉ áp dụng cho đơn takeaway)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn thành'), ('canceled', 'Đã hủy')], max_length=50),
        ),
    ]
