# Generated by Django 5.2.6 on 2025-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_order_dia_chi_giao_hang_order_phuong_thuc_giao_hang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phuong_thuc_giao_hang',
            field=models.CharField(blank=True, choices=[('Tự đến lấy', 'Tự đến lấy'), ('Giao hàng tận nơi', 'Giao hàng tận nơi')], help_text='Phương thức giao hàng (chỉ áp dụng cho đơn takeaway)', max_length=20, null=True),
        ),
    ]
