# Generated by Django 5.2.6 on 2025-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='phi_giao_hang',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Phí giao hàng (nếu có)', max_digits=10),
        ),
    ]
