# Generated by Django 5.2.6 on 2025-11-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
