# Generated by Django 5.2.6 on 2025-11-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_notification_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khach_hang_xac_nhan_thanh_toan',
            field=models.BooleanField(default=False, help_text='Khách hàng đã xác nhận thanh toán'),
        ),
    ]
