# Generated by Django 5.2.6 on 2025-11-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_order_khach_hang_xac_nhan_thanh_toan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khuyen_mai', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('loai_giam_gia', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed_amount', 'Số tiền cố định')], max_length=50)),
                ('gia_tri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
