# Generated by Django 5.2.6 on 2025-11-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_khuyenmai'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='gia_giam',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng giá trị giảm giá (nếu có)', max_digits=10),
        ),
    ]
