# Generated by Django 5.2.6 on 2025-11-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_hoadon_gia_giam'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='khuyen_mai',
            field=models.ManyToManyField(blank=True, help_text='Khuyến mãi áp dụng cho hóa đơn này', related_name='hoa_don', to='restaurant.khuyenmai'),
        ),
    ]
