# Generated by Django 5.2.6 on 2025-11-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_hoadon_khuyen_mai'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='banner_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
