# Generated by Django 5.2.6 on 2025-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_khuyenmai_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='notified_10_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donhang',
            name='notified_1_hour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donhang',
            name='notified_30_min',
            field=models.BooleanField(default=False),
        ),
    ]
